[alembic]
script_location = src/meal_planner/repository/migrations

# The SQLAlchemy URL to the database. Can be overridden using environment variables or
# by setting `sqlalchemy.url` in an Alembic config file.
# sqlalchemy.url = sqlite+aiosqlite:///./src/meal_planner.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
