"""Add food_entry and nutrition_record tables

Revision ID: 595f3357973e
Revises: 0002_recipe_tables
Create Date: 2026-03-18 01:57:08.721129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595f3357973e'
down_revision: Union[str, Sequence[str], None] = '0002_recipe_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_entry',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.Enum('USDA', 'OPEN_FOOD_FACTS', 'BARCODE', 'USER_CREATED', 'CALCULATED', name='foodsourcetype'), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_entry_id'), 'food_entry', ['id'], unique=True)
    op.create_index(op.f('ix_food_entry_name'), 'food_entry', ['name'], unique=False)
    op.create_index(op.f('ix_food_entry_user_id'), 'food_entry', ['user_id'], unique=False)
    op.create_table('nutrition_record',
    sa.Column('food_entry_id', sa.String(length=36), nullable=False),
    sa.Column('serving_size', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('serving_unit', sa.String(length=50), nullable=False),
    sa.Column('calories', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('carbohydrates_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('added_sugar_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fiber_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_sugar_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sodium_mg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('saturated_fat_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source_type', sa.Enum('LABEL', 'BARCODE', 'USER_CONFIRMED', 'ESTIMATED', 'CALCULATED', name='nutritionsourcetype'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['food_entry_id'], ['food_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_record_food_entry_id'), 'nutrition_record', ['food_entry_id'], unique=False)
    op.create_index(op.f('ix_nutrition_record_id'), 'nutrition_record', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_nutrition_record_id'), table_name='nutrition_record')
    op.drop_index(op.f('ix_nutrition_record_food_entry_id'), table_name='nutrition_record')
    op.drop_table('nutrition_record')
    op.drop_index(op.f('ix_food_entry_user_id'), table_name='food_entry')
    op.drop_index(op.f('ix_food_entry_name'), table_name='food_entry')
    op.drop_index(op.f('ix_food_entry_id'), table_name='food_entry')
    op.drop_table('food_entry')
